### ISSUE TITLE
Roll evaluation in v12 resulting in always surge

### ISSUE THREAD

**Issue by Bfrench6** [vtt-lair/simbuls-wild-surges#6]
Currently, in v12, the module considers all rolls a surge. Making this one addition fixes that to no longer be the case.
![image](https://github.com/vtt-lair/simbuls-wild-surges/assets/12520977/70be130c-12da-4b8d-9779-9e3fc7b4947e)
Unsure if there's necessarily a better solution, but this worked to resolve the issue for me.

**Comment by vtt-lair** [comment]
Thanks, I've not had a chance to look at my modules in version 12 yet. 

You are welcome to also create a merge request with the changes if you want and I'll merge it in.

**Comment by vtt-lair** [comment]
Fixed and released
